version: "3.9"

services:
  client:
    build: ./client
    container_name: next_client
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - server

  server:
    build: ./server
    container_name: api_server
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server
